### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ktaranov** [CoderAllan/SqlServerSearcher#2]
What about some License description? I can add MIT in your repo with pull request (like here: https://github.com/ktaranov/sqlserver-kit/blob/master/LICENSE.md) or you want another license type?

**Comment by CoderAllan** [comment]
I dont think i understand what you want me to do. 
In my repo there is already a license file: https://github.com/CoderAllan/SqlServerSearcher/blob/master/LICENSE
So where do you mean it is missing? Should it be mentioned in the README.md?

**Comment by ktaranov** [comment]
Sorry, my fault, did not see this file.
